...

diff --git a/modules/oem-bundle-manager.mod/rtd-oem-bundle-manager b/modules/oem-bundle-manager.mod/rtd-oem-bundle-manager
--- a/modules/oem-bundle-manager.mod/rtd-oem-bundle-manager
+++ b/modules/oem-bundle-manager.mod/rtd-oem-bundle-manager
@@ -307,7 +307,11 @@ system::ExecStart::help ()
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-dependency::file "_rtd_library" || { echo "📚 Failed to find _rtd_library"; exit 1; }
+if [ -z "${RTDFUNCTIONS}" ]; then
+	dependency::file _rtd_library &>/dev/null|| { echo "📚 Failed to find _rtd_library"; exit 1; }
+else
+	write_information "📚 _rtd_library is already loaded..."
+fi
 
 main ()
 {
diff --git a/modules/simple-support-tool.mod/rtd-simple-support-tool b/modules/simple-support-tool.mod/rtd-simple-support-tool
--- a/modules/simple-support-tool.mod/rtd-simple-support-tool
+++ b/modules/simple-support-tool.mod/rtd-simple-support-tool
@@ -1292,7 +1292,12 @@ case $1 in
 	* )
 		if [[ "$TERM" == screen* ]]; then
 			rtd_oem_check_inet_access
-			dependency::file _rtd_library &>/dev/null
+			if [ -z "${RTDFUNCTIONS}" ]; then
+				dependency::file _rtd_library &>/dev/null|| { echo "📚 Failed to find _rtd_library"; exit 1; }
+			else
+				write_information "📚 _rtd_library is already loaded..."
+			fi
+			
 			security::ensure_admin
 			if [ "$UID" -eq 0 ]; then
 				check_menu_availability
@@ -1305,7 +1310,12 @@ case $1 in
 				byobu new-session -s "RTD Simple Server Support Tools" $0
 			else
 				rtd_oem_check_inet_access
-				dependency::file _rtd_library &>/dev/null
+				if [ -z "${RTDFUNCTIONS}" ]; then
+					dependency::file _rtd_library &>/dev/null|| { echo "📚 Failed to find _rtd_library"; exit 1; }
+				else
+					write_information "📚 _rtd_library is already loaded..."
+				fi
+				
 				security::ensure_admin
 				if [ "$UID" -eq 0 ]; then
 					software::check_native_package_dependency byobu && echo -e "$RED" "A critical component needed for this script to work properly was attempted to be added... Attempting to run the script again"
