Aligned w. Google guide

diff --git a/modules/oem-system-admin.mod/rtd-7z-all-files-here b/modules/oem-system-admin.mod/rtd-7z-all-files-here
--- a/modules/oem-system-admin.mod/rtd-7z-all-files-here
+++ b/modules/oem-system-admin.mod/rtd-7z-all-files-here
@@ -133,7 +133,7 @@ if [[ $1 == "--help" ]]; then
 fi
 
 # Ensure access to the rtd library functions:
-dependency_library || { echo -e "RTD functions NOT found!"; exit 1; }
+dependency_library || { echo "Library not found!" ; exit 1 ; }
 
 # call compression function with its default behavior...
 tool::compress_all_items_here || { write_error -e "Compression failed!"; exit 1; }
diff --git a/modules/oem-system-admin.mod/rtd-burniso b/modules/oem-system-admin.mod/rtd-burniso
--- a/modules/oem-system-admin.mod/rtd-burniso
+++ b/modules/oem-system-admin.mod/rtd-burniso
@@ -76,7 +76,7 @@ dependency_library ()
 ###########################################################################
 
 # Ensure access to the rtd library functions:
-dependency_library || { write_error "clamav not found!" ; exit 1 ; }
+dependency_library || { echo "Library not found!" ; exit 1 ; }
 
 # Check syntax this script is called with:
 if [[ -z "$1" ]]; then
diff --git a/modules/oem-system-admin.mod/rtd-configure-huion b/modules/oem-system-admin.mod/rtd-configure-huion
--- a/modules/oem-system-admin.mod/rtd-configure-huion
+++ b/modules/oem-system-admin.mod/rtd-configure-huion
@@ -71,7 +71,7 @@ if dependency_library ; then
 	# Attempt config of HUION:
 	config_huion610
 else
-	write_error "RTD functions NOT found!"
+	{ echo "Library not found!" ; exit 1 ; }
 	exit 1
 fi
 
diff --git a/modules/oem-system-admin.mod/rtd-join-avi b/modules/oem-system-admin.mod/rtd-join-avi
--- a/modules/oem-system-admin.mod/rtd-join-avi
+++ b/modules/oem-system-admin.mod/rtd-join-avi
@@ -71,7 +71,7 @@ dependency_library ()
 #::::::::::::::          Script Executive                ::::::::::::::::::::::
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-dependency_library || { write_error "Llibrary not found!" ; exit 1 ; }
+dependency_library || { echo "Library not found!" ; exit 1 ; }
 
 if ! hash mencoder 2>/dev/null; then
 	if [[ "$UID" == "0" ]]; then
diff --git a/modules/oem-system-admin.mod/rtd-mv b/modules/oem-system-admin.mod/rtd-mv
--- a/modules/oem-system-admin.mod/rtd-mv
+++ b/modules/oem-system-admin.mod/rtd-mv
@@ -169,7 +169,7 @@ if [ "$1" = "--help" ]; then display_help ; fi
 if [ "$1" = "" ]; then display_help ; fi
 
 exec_task () {
-	dependency_library || { write_error "Llibrary not found!" ; exit 1 ; }
+	dependency_library || { echo "Library not found!" ; exit 1 ; }
 	build_file_list
 
 	if ($rtd_menu --fb  --title "$BRANDING" --yesno "I found $number_of_files_to_move files for $filetype type to move. Do you want to proceed?  $todo" 15 95); then
