Minor adjustments for consistency

diff --git a/modules/oem-system-admin.mod/rtd-deb-cleanup b/modules/oem-system-admin.mod/rtd-deb-cleanup
--- a/modules/oem-system-admin.mod/rtd-deb-cleanup
+++ b/modules/oem-system-admin.mod/rtd-deb-cleanup
@@ -107,45 +107,50 @@ rtd_oem_clean_deb ()
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
 # Ensure access to the rtd library functions:
-dependency::_rtd_library
+if dependency::_rtd_library ; then
+	conditional_run ()
+	{
+		if [[ $(echo "$OSTYPE" |grep "linux") ]]; then
 
+			# Only run these cleanup function on a debian based system.
+			if cat /etc/os-release |grep "debian" 2>/dev/null ; then
+				# Ensure elevated privs:
+				ensure_admin
 
+				# Display information about script:
+				result="This utility will clean up old kernels, orphaned configurations, and cached packages from completed installs. Please note that you may run this utility more than once if a cleanup changes the profile of the system; for example if an updated kernel is added ass part of the process."
+				display_result $( basename $0 : Notice!)
 
-conditional_run ()
-{
-	if [[ $(echo "$OSTYPE" |grep "linux") ]]; then
+				# Complete cleanup:
+				rtd_oem_clean_deb
+				return $?
+			else
+				# Notify if this system is not debian.
+				result="This system does not appear to be Debian based. This cleanup is only intended for the debian based systems that use the 'apt' software managment system."
+				display_result $( basename $0 : Notice!)
+			fi
 
-		# Only run these cleanup function on a debian based system.
-		if cat /etc/os-release |grep "debian" 2>/dev/null ; then
-			# Ensure elevated privs:
-			ensure_admin
-
-			# Display information about script:
-			result="This utility will clean up old kernels, orphaned configurations, and cached packages from completed installs. Please note that you may run this utility more than once if a cleanup changes the profile of the system; for example if an updated kernel is added ass part of the process."
-			display_result $( basename $0 : Notice!)
-
-			# Complete cleanup:
-			rtd_oem_clean_deb
-			return $?
+		elif [[ "$OSTYPE" == "darwin"* ]]; then
+			write_error "${FUNCNAME[0]}: Mac OSX is currently not supported ..."  ; return 1
+		elif [[ "$OSTYPE" == "cygwin" ]]; then
+			write_error "${FUNCNAME[0]}: CYGWIN is currently unsupported ..."  ; return 1
+		elif [[ "$OSTYPE" == "msys" ]]; then
+			write_error "${FUNCNAME[0]}: Lightweight shell is currently unsupported ... "  ; return 1
+		elif [[ "$OSTYPE" == "freebsd"* ]]; then
+			write_error "${FUNCNAME[0]}: Free BSD is currently unsupported ... " ; return 1
 		else
-			# Notify if this system is not debian.
-			result="This system does not appear to be Debian based. This cleanup is only intended for the debian based systems that use the 'apt' software managment system."
-			display_result $( basename $0 : Notice!)
+			echo "I have no Idea what this system is: aborting!" ; return 1
 		fi
+	}
+	conditional_run
+else
+	write_error "RTD functions NOT found!"
+	exit 1
+fi
 
-	elif [[ "$OSTYPE" == "darwin"* ]]; then
-		write_error "${FUNCNAME[0]}: Mac OSX is currently not supported ..."  ; return 1
-	elif [[ "$OSTYPE" == "cygwin" ]]; then
-		write_error "${FUNCNAME[0]}: CYGWIN is currently unsupported ..."  ; return 1
-	elif [[ "$OSTYPE" == "msys" ]]; then
-		write_error "${FUNCNAME[0]}: Lightweight shell is currently unsupported ... "  ; return 1
-	elif [[ "$OSTYPE" == "freebsd"* ]]; then
-		write_error "${FUNCNAME[0]}: Free BSD is currently unsupported ... " ; return 1
-	else
-		echo "I have no Idea what this system is: aborting!" ; return 1
-	fi
-}
-conditional_run
+
+
+
 
 
 
diff --git a/modules/oem-system-admin.mod/rtd-dropbox-on-ecryptfs b/modules/oem-system-admin.mod/rtd-dropbox-on-ecryptfs
--- a/modules/oem-system-admin.mod/rtd-dropbox-on-ecryptfs
+++ b/modules/oem-system-admin.mod/rtd-dropbox-on-ecryptfs
@@ -55,22 +55,26 @@ dependency::_rtd_library ()
 
 
 
-dependency::_rtd_library
+if dependency::_rtd_library ; then
+        if [[ -d ~/Dropbox ]]; then
+                killall dropbox
+                mv Dropbox Dropbox.bak
+                mkdir Dropbox
+                dd if=/dev/zero of=~/.dropbox/storage bs=1M count=14072
+                mkfs.ext4 /home/$USER/.dropbox/storage
+                chattr +i /home/$USER/Dropbox
+                /home/$USER/.dropbox/storage /home/$USER/Dropbox ext4 defaults,user_xattr,loop 0 0
+                mount /home/$USER/Dropbox/
 
-if [[ -d ~/Dropbox ]]; then
-        killall dropbox
-        mv Dropbox Dropbox.bak
-        mkdir Dropbox
-        dd if=/dev/zero of=~/.dropbox/storage bs=1M count=14072
-        mkfs.ext4 /home/$USER/.dropbox/storage
-        chattr +i /home/$USER/Dropbox
-        /home/$USER/.dropbox/storage /home/$USER/Dropbox ext4 defaults,user_xattr,loop 0 0
-        mount /home/$USER/Dropbox/
 
-
-        chown -R $USER /home/$USER/Dropbox
-        cp -a Dropbox.bak/* Dropbox/
+                chown -R $USER /home/$USER/Dropbox
+                cp -a Dropbox.bak/* Dropbox/
+        else
+                echo "Dropbox folder not found!"
+                exit 1
+        fi
 else
-        echo "Dropbox folder not found!"
+        write_information "RTD functions NOT found!"
         exit 1
 fi
+
