...

diff --git a/core/_rtd_library b/core/_rtd_library
--- a/core/_rtd_library
+++ b/core/_rtd_library
@@ -347,7 +347,7 @@ github::list_all_user_repositories ()
 	if [ $# -eq 0 ]
 	  then
 	    echo "Usage: ${FUNCNAME[0]} <user_name> "
-	    exit 1;
+	    return 1;
 	fi
 
 	for repo in $(curl -s https://api.github.com/users/${1}/repos?per_page=1000 |grep git_url |awk '{print $2}'| sed 's/"\(.*\)",/\1/'); do
@@ -898,73 +898,73 @@ display_spinner ()
 #
 # End of documentation
 
-		function _spinner() {
-		# $1 start/stop
-		#
-		# on start: $2 display message
-		# on stop : $2 process exit status
-		#           $3 spinner function pid (supplied from stop_spinner)
+	function _spinner() {
+	# $1 start/stop
+	#
+	# on start: $2 display message
+	# on stop : $2 process exit status
+	#           $3 spinner function pid (supplied from stop_spinner)
 
-		local on_success="DONE"
-		local on_fail="FAIL"
-		local nc="\e[0m"
+	local on_success="DONE"
+	local on_fail="FAIL"
+	local nc="\e[0m"
 
-		case $1 in
-			start)
-			# calculate the column where spinner and status msg will be displayed
-			let column=$(tput cols)-${#2}-46
-			# display message and position the cursor in $column column
-			# echo -ne ${2}
-			printf "%${column}s"
+	case $1 in
+		start)
+		# calculate the column where spinner and status msg will be displayed
+		let column=$(tput cols)-${#2}-46
+		# display message and position the cursor in $column column
+		# echo -ne ${2}
+		printf "%${column}s"
 
-			# start spinner
-			i=1
-			sp='\|/-'
-			delay=${SPINNER_DELAY:-0.15}
+		# start spinner
+		i=1
+		sp='\|/-'
+		delay=${SPINNER_DELAY:-0.15}
 
-			while :
-			do
-				printf "${RED}\b[${sp:i++%${#sp}:1}]\b\b${ENDCOLOR}"
-				sleep $delay
-			done
-			;;
-			stop)
-			if [[ -z ${3} ]]; then
-				echo "spinner is not running.."
-				exit 1
-			fi
-
-			kill $3 > /dev/null 2>&1
-
-			# inform the user uppon success or failure
-			echo -en "\b["
-			if [[ $2 -eq 0 ]]; then
-				echo -en "${green}${on_success}${nc}"
-			else
-				echo -en "${red}${on_fail}${nc}"
-			fi
-			echo -e "]"
-			;;
-			*)
-			write_error "invalid argument, try {start/stop}"
+		while :
+		do
+			printf "${RED}\b[${sp:i++%${#sp}:1}]\b\b${ENDCOLOR}"
+			sleep $delay
+		done
+		;;
+		stop)
+		if [[ -z ${3} ]]; then
+			echo "spinner is not running.."
 			exit 1
-			;;
-		esac
-		}
+		fi
 
-		function start_spinner {
-		# $1 : msg to display
-		_spinner "start" "${1}" &
-		# set global spinner pid
-		export _sp_pid=$!
-		disown
-		}
+		kill $3 > /dev/null 2>&1
 
-		function stop_spinner {
-		# $1 : command exit status
-		_spinner "stop" $1 $_sp_pid
-		unset _sp_pid
-		}
+		# inform the user uppon success or failure
+		echo -en "\b["
+		if [[ $2 -eq 0 ]]; then
+			echo -en "${green}${on_success}${nc}"
+		else
+			echo -en "${red}${on_fail}${nc}"
+		fi
+		echo -e "]"
+		;;
+		*)
+		write_error "invalid argument, try {start/stop}"
+		exit 1
+		;;
+	esac
+	}
+
+	function start_spinner {
+	# $1 : msg to display
+	_spinner "start" "${1}" &
+	# set global spinner pid
+	export _sp_pid=$!
+	disown
+	}
+
+	function stop_spinner {
+	# $1 : command exit status
+	_spinner "stop" $1 $_sp_pid
+	unset _sp_pid
+	}
 
 	if [[ "$1" == "start" ]] ; then
 		start_spinner $2
