Added shell exec priv escalation.

diff --git a/core/_rtd_library b/core/_rtd_library
--- a/core/_rtd_library
+++ b/core/_rtd_library
@@ -2292,34 +2292,42 @@ ensure_admin ()
 #
 # End of documentation
 
+	_exec_local="$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/"$( basename ${0} )"
 
 	if [ ! "$UID" -eq 0 ]; then
-		# Session is NOT priviledged; relaunch script with priviledges to do system admin...
-		write_information "Allowing root to display menus..."
-		if xset q &>/dev/null; then xhost local:root ; fi
-		if hash dialog 2>/dev/null ; then
-			# find  a diferent way... tempfile not universal...
-			token=$(dialog --title "${Title:-"sudo"}" --backtitle "${BackTitle:-"$( basename $0 )"}" --insecure --stdout --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90)
-			ret=$? ; clear
-			case $ret in
-				0)
-					export HISTIGNORE='*sudo -S*'
-					echo ${token} | sudo -S -v || ensure_admin
-					# Another workaround just for SUSE...
-					sudo sed -i s/'# session  optional       pam_xauth.so'/'session  optional       pam_xauth.so'/g /etc/pam.d/sudo
-					sudo DISPLAY=$DISPLAY /bin/bash $0 $@ || rtd_oem_pause 1
-				;;
-				1) echo "Request cancelled" ;;
-				255) echo "[esc] Request aborted" ;;
-				* )  exit 1
-			esac
-			exit
+		if echo $(systemctl get-default ) |grep graphical &>/dev/null ; then
+			if xset q &>/dev/null; then xhost local:root ; fi
+			pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY ${_exec_local}
 		else
-			write_warning "This script needs administrative access..."
-			sudo DISPLAY=$DISPLAY bash "$0" "$@" || rtd_oem_pause 1
-			exit
+			# Session is NOT priviledged; relaunch script with priviledges to do system admin...
+			write_information "Allowing root to display menus..."
+			if xset q &>/dev/null; then xhost local:root ; fi
+			if hash dialog 2>/dev/null ; then
+				# find  a diferent way... tempfile not universal...
+				token=$(dialog --title "${Title:-"sudo"}" --backtitle "${BackTitle:-"$( basename $0 )"}" --insecure --stdout --passwordbox "\n This functionality requires elevated priviledges. \n Please provide your (sudo) password" 10 90)
+				ret=$? ; clear
+				case $ret in
+					0)
+						export HISTIGNORE='*sudo -S*'
+						echo ${token} | sudo -S -v || ensure_admin
+						sudo DISPLAY=$DISPLAY /bin/bash ${_exec_local} $@ || rtd_oem_pause 1
+					;;
+					1) echo "Request cancelled" ;;
+					255) echo "[esc] Request aborted" ;;
+					* )  exit 1
+				esac
+				exit
+			else
+				write_warning "This script needs administrative access..."
+				if xset q &>/dev/null; then xhost local:root ; fi
+				sudo DISPLAY=$DISPLAY bash "${_exec_local}" "$@" || rtd_oem_pause 1
+				exit
+			fi
 		fi
+	else
+		sudo sed -i s/'# session  optional       pam_xauth.so'/'session  optional       pam_xauth.so'/g /etc/pam.d/sudo
 	fi
+
 }
 
 
