....

diff --git a/core/_rtd_library b/core/_rtd_library
--- a/core/_rtd_library
+++ b/core/_rtd_library
@@ -4506,36 +4506,51 @@ ensure_flatpak_package_managment ()
 # | Plugins for Desktop App Store Software             | Yes         | Yes         | No           |
 # +----------------------------------------------------+-------------+-------------+--------------+
 # End of documentation
-	if hash flatpak ; then
-		write_status "🧩 ${FUNCNAME[0]}: flatpak command is available... "
-		if flatpak remotes | grep flathub ; then 
-			write_status "🧩 ${FUNCNAME[0]}: Flathub remote is present..."
+	if [[ $(echo "$OSTYPE" |grep "linux") ]] &>/dev/null ; then
+		# these tests focus on the latest versions of the distros evaluated...
+		write_information "ensuring SNAP software distribution system is available..."
+		if hash flatpak ; then
+			write_status "flatpak command is available... "
+			if flatpak remotes | grep flathub  &>/dev/null ; then 
+				write_status "flathub remote is present..."
+			else
+				write_warning "flathub remote is not present... adding now... "
+				ensure_admin
+				flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || write_error "Failed to add flatpak repo!"
+			fi
+
+			if flatpak list|grep com.github.tchx84.Flatseal  &>/dev/null ; then 
+				write_status "flatseal security management is also present..."
+			else
+				ensure_admin
+				write_status "flatseal security manager not found, adding now..."
+				flatpak install flathub com.github.tchx84.Flatseal --noninteractive -y
+			fi
 		else
-			write_warning "🧩 ${FUNCNAME[0]}: Flathub remote is not present... adding now... "
 			ensure_admin
-			flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || write_error "💥 ${FUNCNAME[0]}: Failed to add flatpak repo!"
+			write_information "Ensuring Flatpak software distribution system is available..."
+				check_dependencies flatpak || write_error "Failed to satisfy dependecy flatpak!"
+				flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || write_error "Failed to add flatpak repo!"
+			if flatpak list|grep com.github.tchx84.Flatseal  &>/dev/null ; then 
+				write_status "flatseal security management is also present..."
+			else
+				ensure_admin
+				write_status "flatseal security manager not found, adding now..."
+				flatpak install flathub com.github.tchx84.Flatseal --noninteractive -y
+			fi
+			return $?
 		fi
 
-		if flatpak list|grep com.github.tchx84.Flatseal ; then 
-			write_status "🧩 ${FUNCNAME[0]}: flatseal security management is also present..."
-		else
-			ensure_admin
-			write_status "🧩 ${FUNCNAME[0]}: flatseal security manager not found, adding now..."
-			flatpak install flathub com.github.tchx84.Flatseal --noninteractive -y
-		fi
+	elif [[ "$OSTYPE" == "darwin"* ]]; then
+		write_error "${FUNCNAME[0]}: Mac OSX is currently not supported with snap..."  ; return 1
+	elif [[ "$OSTYPE" == "cygwin" ]]; then
+		write_error "${FUNCNAME[0]}: CYGWIN is currently unsupported with snap..."  ; return 1
+	elif [[ "$OSTYPE" == "msys" ]]; then
+		write_error "${FUNCNAME[0]}: Lightweight shell is currently unsupported with snap... "  ; return 1
+	elif [[ "$OSTYPE" == "freebsd"* ]]; then
+		write_error "${FUNCNAME[0]}: Free BSD is currently unsupported with snap... " ; return 1
 	else
-		ensure_admin
-		write_information "🧩 ${FUNCNAME[0]}: Ensuring Flatpak software distribution system is available..."
-			check_dependencies flatpak || write_error "💥 ${FUNCNAME[0]}: Failed to satisfy dependecy flatpak!"
-			flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || write_error "💥 ${FUNCNAME[0]}: Failed to add flatpak repo!"
-		if flatpak list|grep com.github.tchx84.Flatseal ; then 
-			write_status "🧩 ${FUNCNAME[0]}: flatseal security management is also present..."
-		else
-			ensure_admin
-			write_status "🧩 ${FUNCNAME[0]}: flatseal security manager not found, adding now..."
-			flatpak install flathub com.github.tchx84.Flatseal --noninteractive -y
-		fi
-		return $?
+		echo "I have no Idea what this system is" ; return 1
 	fi
 }
 
@@ -4591,47 +4606,61 @@ ensure_snap_package_managment ()
 # End of documentation
 
 
-	if [[ $(echo "$OSTYPE" |grep "linux") ]]; then
-		ensure_admin
+	if [[ $(echo "$OSTYPE" |grep "linux") ]] &>/dev/null ; then
 		# these tests focus on the latest versions of the distros evaluated...
+		write_information "ensuring SNAP software distribution system is available..."
 		if hostnamectl |grep "SUSE" 2>/dev/null ; then
-			write_warning "🧩 ${FUNCNAME[0]}: Special case for suse"
-			hash snap && ( return 0 & write_status "🧩 ${FUNCNAME[0]}:Snap is already present" )
-		
-			if hostnamectl |grep -i "tumbleweed" ; then
-				zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed || ( write_error "💥 ${FUNCNAME[0]}: Failed to add snap repo!" ; return 1 )
+			write_warning "Special case for suse"
+			if hash snap &>/dev/null ; then
+				write_status "Snap is already present..."
+				return 0
 			else
-				zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_$(cat /etc/os-release |grep VERSION_ID |cut -d= -f2|cut -d\" -f2) snappy || ( write_error "💥 ${FUNCNAME[0]}: Failed to add snap repo!" ; return 1 )
-			fi
-				zypper --gpg-auto-import-keys refresh || ( write_error "💥 ${FUNCNAME[0]}: Failed to gpg keys!" ; return 1 )
-				zypper dup --from snappy || ( write_error "💥 ${FUNCNAME[0]}: Failed to update snap repository!" ; return 1 )
-				check_dependencies snapd || ( write_error "💥 ${FUNCNAME[0]}: Failed to satisfy dependecy SNAP!" ; return 1 )
+				ensure_admin
+				if hostnamectl |grep -i "tumbleweed" ; then
+					zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed || ( write_error "Failed to add snap repo!" ; return 1 )
+				else
+					zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_$(cat /etc/os-release |grep VERSION_ID |cut -d= -f2|cut -d\" -f2) snappy || ( write_error "Failed to add snap repo!" ; return 1 )
+				fi
+				zypper --gpg-auto-import-keys refresh || ( write_error "Failed to gpg keys!" ; return 1 )
+				zypper dup --from snappy || ( write_error "Failed to update snap repository!" ; return 1 )
+				check_dependencies snapd || ( write_error "Failed to satisfy dependecy SNAP!" ; return 1 )
 				systemctl enable snapd ; systemctl start snapd
-				systemctl is-active --quiet snapd || ( write_error "💥 ${FUNCNAME[0]}: Service snapd not started sucessfully!" ; return 1 )
+				systemctl is-active --quiet snapd || ( write_error "Service snapd not started sucessfully!" ; return 1 )
 				ln -s /var/lib/snapd/snap /snap
-			return $?
+				return $?
+			fi
 		elif hostnamectl |grep "Ubuntu" 2>/dev/null ; then
-			write_information "🧩 ${FUNCNAME[0]}: Ubuntu has snap support built in..." ;return 0
+			write_information "Ubuntu has snap support built in..." ;return 0
 		elif hostnamectl |grep "Zorin" 2>/dev/null ; then
-			write_information "🧩 ${FUNCNAME[0]}: Zorin has snap support built in..." ;return 0
+			write_information "Zorin has snap support built in..." ;return 0
 		else
 			# For distributions that do not need to add a repository to install snap
 			# But would need to install it from their standard reopsitory....
-			write_information "${FUNCNAME[0]}: Ensuring SNAP software distribution system is available..."
-			hash snap && ( return 0 & write_status "🧩 ${FUNCNAME[0]}:Snap is already present" )
-			if check_dependencies snapd ; then
-				systemctl enable snapd ; systemctl start snapd
-				echo snapd is $(systemctl is-active snapd) || return 1
+			if hash snap &>/dev/null ; then
+				write_status "Snap is already present..."
+				if [[ -e /snap ]]; then
+					write_information "SNAP classic support present... "
+				else
+					write_information "SNAP classic support NOT present... "
+					write_information "adding links... "
+					ln -s /var/lib/snapd/snap /snap
+				fi
+				return $?
 			else
-				write_error "💥 ${FUNCNAME[0]}: Failed to satisfy dependecy SNAP!"
-			fi
+				if check_dependencies snapd ; then
+					systemctl enable snapd ; systemctl start snapd
+					echo snapd is $(systemctl is-active snapd) || return 1
+				else
+					write_error "Failed to satisfy dependecy SNAP!"
+				fi
 
-			if [[ -e /snap ]]; then
-				write_information "SNAP classic support present... "
-			else
-				ln -s /var/lib/snapd/snap /snap
+				if [[ -e /snap ]]; then
+					write_information "SNAP classic support present... "
+				else
+					ln -s /var/lib/snapd/snap /snap
+				fi
+				return $?
 			fi
-			return $?
 		fi
 
 	elif [[ "$OSTYPE" == "darwin"* ]]; then
@@ -5344,6 +5373,220 @@ rtd_update_system ()
 
 
 
+
+
+
+software::from_flathub.org ()
+{
+# Description: Function to simplify and streamline the installation and removal of flatpaks.
+# Globals: none
+# Dependencies: [distro pakage managment] [function: check_dependencies] [Internet access]
+# Arguments: 
+# -- Default action is to add software title matching passed parameter. 
+# -- An optioin "--remove" may be passed to atempt removal of the software title. 
+#
+# Outputs:
+# Returns: Standard return codes 1/0
+# Usage: software::from_flathub.org [ title-name | title-name --remove ]
+#
+# 
+# NOTE: https://www.fosslinux.com/42410/snap-vs-flatpak-vs-appimage-know-the-differences-which-is-better.htm
+# Like Snap, Flatpak is another distribution independent package format aimed to simplify overall
+# app distribution and usage in Linux systems. Previously known as xdg-app, the framework was based
+# on the concept of running applications in a secure virtual sandbox without requiring root privileges
+# or posing a security threat to the system.
+#
+#	*	---       PREFFERRED Software install for GUI apps           ----		*
+#
+#  CAPABILITY TABLE:
+# +----------------------------------------------------+-------------+-------------+--------------+
+# | Features                                           | Snap        | Flatpak     | AppImage     |
+# +----------------------------------------------------+-------------+-------------+--------------+
+# | Permission Controls Toggles                        | Yes         | Yes         | No           |
+# | Sandboxing Support                                 | Yes         | Yes         | Yes          |
+# | Sandboxing Mandatory                               | Yes         | Yes         | No           |
+# | App Portability                                    | Yes         | Yes         | No           |
+# | Native Theme Support                               | Yes (caveat)| Yes (caveat)| Yes (caveat) |
+# | Support for Bundled Libraries                      | Yes         | Yes         | Yes          |
+# | Fully Contained Single Executable Support          | No          | No          | Yes          |
+# | Online App Store                                   | Yes         | Yes         | Yes          |
+# | Multi-version Parallel Apps Support                | Yes         | Yes         | Yes          |
+# | Automatic Updates                                  | Yes         | Yes         | Yes (caveat) |
+# | Support for Chrome OS (through Crostini containers)| Yes         | Yes         | Yes          |
+# | App Size                                           | higher than | higher than | Lowest       |
+# | Number of Applications Available in the App Store  | Highest     | Lowest      | Somewhere in |
+# | Plugins for Desktop App Store Software             | Yes         | Yes         | No           |
+# +----------------------------------------------------+-------------+-------------+--------------+
+# End of documentation
+
+	local app_name=""
+	local remove_flag=""
+
+	# Parse command line arguments
+	while [[ $# -gt 0 ]]; do
+		case "$1" in
+		--remove)
+			remove_flag="--remove"
+			shift
+		;;
+		*)
+			if [[ -z "$app_name" ]]; then
+				app_name="$1"
+			else
+				write_error "Error: Invalid parameter '$1'"
+				write_information "Usage: software::from_flathub.org [app_name] [--remove]"
+				return 1
+			fi
+			shift
+		;;
+		esac
+	done
+
+	hash flatpak || ensure_flatpak_package_managment
+
+	if [[ -z "$app_name" ]]; then
+		write_error "Error: App name is missing."
+		write_information "Usage: software::from_flathub.org [app_name] [--remove]"
+		return 1
+	fi
+
+	if [[ "$remove_flag" == "--remove" ]]; then
+		
+		if flatpak uninstall -y "$app_name"; then
+			write_information "Flatpak app '$app_name' has been uninstalled."
+		else
+			write_error "Error: Failed to uninstall Flatpak app '$app_name'"
+			return 1
+		fi
+	else
+		
+		if flatpak info "$app_name" >/dev/null 2>&1; then
+			write_information "Flatpak app '$app_name' is already installed."
+		else
+			if flatpak install -y "$app_name"; then
+				write_information "Flatpak app '$app_name' has been installed."
+			else
+				write_error "Error: Failed to install Flatpak app '$app_name'"
+				return 1
+			fi
+		fi
+	fi
+}
+
+
+
+
+
+
+software::from_snapcraft.io ()
+{
+# Description: Function to ensure that snap is installed.
+# Globals: none
+# Dependencies: [distro pakcage managment] [function: check_dependencies] [Internet access]
+# Arguments: None
+# Outputs: stdout
+# Returns: Standard return codes 1/0
+# Usage: Call the function with no arguments
+# NOTE:
+# https://www.fosslinux.com/42410/snap-vs-flatpak-vs-appimage-know-the-differences-which-is-better.htm
+# Snap is a distribution independent package format developed by Canonical and first released
+# in 2014. It was initially developed for Ubuntu but has been adopted by other Linux distributions
+# like Arch, Linux Mint, CentOS, Gentoo, and Fedora, and also included support for the Snap
+# framework. The main aim behind this package format development was to come up with a
+# single unified format for software packages to run in a wide range of devices.
+# That includes IoT (IoT), embedded devices running Ubuntu Core (a minimalistic
+# version of Ubuntu), and computer systems that ran some Ubuntu version.
+# Snap also offers an online app store – Snapcraft, where users can find and
+# install the software packages. It creates a large pool where users can find all
+# available a snap package. Snapcraft is itself controlled and maintained by the
+# Canonical team.
+#
+#
+#	*	---   PREFFERRED Software install for CLI apps        ----	*
+#
+#  CAPABILITY TABLE:
+# +----------------------------------------------------+-------------+-------------+--------------+
+# | Features                                           | Snap        | Flatpak     | AppImage     |
+# +----------------------------------------------------+-------------+-------------+--------------+
+# | Permission Controls Toggles                        | Yes         | Yes         | No           |
+# | Sandboxing Support                                 | Yes         | Yes         | Yes          |
+# | Sandboxing Mandatory                               | Yes         | Yes         | No           |
+# | App Portability                                    | Yes         | Yes         | No           |
+# | Native Theme Support                               | Yes (caveat)| Yes (caveat)| Yes (caveat) |
+# | Support for Bundled Libraries                      | Yes         | Yes         | Yes          |
+# | Fully Contained Single Executable Support          | No          | No          | Yes          |
+# | Online App Store                                   | Yes         | Yes         | Yes          |
+# | Multi-version Parallel Apps Support                | Yes         | Yes         | Yes          |
+# | Automatic Updates                                  | Yes         | Yes         | Yes (caveat) |
+# | Support for Chrome OS (through Crostini containers)| Yes         | Yes         | Yes          |
+# | App Size                                           | higher than | higher than | Lowest       |
+# | Number of Applications Available in the App Store  | Highest     | Lowest      | Somewhere in |
+# | Plugins for Desktop App Store Software             | Yes         | Yes         | No           |
+# +----------------------------------------------------+-------------+-------------+--------------+
+# End of documentation
+
+
+	local app_name=""
+	local remove_flag=""
+	local requires_classic=""
+
+	# Parse command line arguments
+	while [[ $# -gt 0 ]]; do
+		case "$1" in
+		--remove)
+			remove_flag="--remove"
+			shift
+		;;
+		*)
+			if [[ -z "$app_name" ]]; then
+			app_name="$1"
+			else
+				write_error "Error: Invalid parameter '$1'"
+				write_information "Usage: install_or_remove_snap_app [app_name] [--remove]"
+				return 1
+			fi
+			shift
+			continue  # Skip the remaining part of the loop
+			;;
+		esac
+	done
+
+	if [[ -z "$app_name" ]]; then
+		write_error "Error: App name is missing."
+		write_information "Usage: ${FUNCNAME[0]} [app_name] [--remove]"
+		return 1
+	fi
+
+	hash snap || ensure_snap_package_managment
+
+	if [[ "$remove_flag" == "--remove" ]]; then
+		if snap remove "$app_name"; then
+			write_information "Snap app '$app_name' has been removed."
+		else
+			write_error "Error: Failed to remove Snap app '$app_name'"
+		fi
+	else
+		if snap list "$app_name" >/dev/null 2>&1; then
+			write_information "Snap app '$app_name' is already installed."
+		else
+			requires_classic=$(snap info "$app_name" | grep "latest/stable" | grep -o " classic")
+			if [[ -n "$requires_classic" ]]; then
+				write_warning "The app '$app_name' requires classic confinement (less confined)..."
+				if snap install "$app_name" --classic; then
+					write_information "Snap app '$app_name' has been installed."
+				else
+					write_error "Error: Failed to install Snap app '$app_name'"
+				fi
+			else
+				if snap install "$app_name"; then
+					write_information "Snap app '$app_name' has been installed."
+				else
+					write_error "Error: Failed to install Snap app '$app_name'"
+				fi
+			fi
+		fi
+	fi
+}
 
 
 
@@ -9254,7 +9497,7 @@ write_host ()
 		--darkpurple ) color="$(tput dim; tput setaf 5)" ;;
 		*) local _text="$1" ;;
 	esac
-	[[ -z "${_text}" ]] && local _text="${color} $2 $(tput sgr0)"
+	[[ -z "${_text}" ]] && local _text="${color} 💻 $2 $(tput sgr0)"
 	echo -e "${_text} "
 }
 
@@ -9275,7 +9518,7 @@ write_error ()
 
 	local text=$1
 	if [[ -n "${text}" ]]; then
-		echo -e "$(tput bold; tput setaf 1)${text}${endcolor}"
+		echo -e "$(tput bold; tput setaf 1)🧩 💥 ${FUNCNAME[1]}: ${text}${endcolor}"
 	fi
 }
 
@@ -9295,7 +9538,7 @@ write_warning ()
 
 
 	local text=$1
-	[ -n "${text}" ] && echo -e "${yellow}${text}${endcolor}"
+	[ -n "${text}" ] && echo -e "${yellow}🧩 ${FUNCNAME[1]}: ${text}${endcolor}"
 
 }
 
@@ -9315,7 +9558,7 @@ write_status ()
 
 
 	local text=$1
-	[ -n "${text}" ] && echo -e "${green}${text}${endcolor}"
+	[ -n "${text}" ] && echo -e "${green}🧩 ${FUNCNAME[1]}: ${text}${endcolor}"
 
 }
 
@@ -9335,7 +9578,7 @@ write_information ()
 
 
 	local text=$1
-	[ -n "${text}" ] && echo -e "${blue}${text}${endcolor}"
+	[ -n "${text}" ] && echo -e "${blue}🧩 ${FUNCNAME[1]}: ${text}${endcolor}"
 
 }
 
