...

diff --git a/core/_rtd_library b/core/_rtd_library
--- a/core/_rtd_library
+++ b/core/_rtd_library
@@ -14070,10 +14070,31 @@ kvm::util::read_distro_options() {
 					fi
 					shift 2
 					;;
-				--product | --product)
+				--product )
 					if [[ $2 == "Leap" || $2 == "SLES" || $2 == "Tumbleweed" ]]; then
 						_UserProductSelection="$2"
 						system::log_item "Product selection: ${_UserProductSelection}"
+
+						# Set the default source URL for the SUSE version if not already set...
+						# NOTE: Using --source_url first, then the global variable (from _locations.info), then the default.
+						case ${_UserProductSelection} in
+							"Leap")
+								: ${source_url:="${_SUSE_LEAP_SOURCE:-"https://download.opensuse.org/distribution/openSUSE-current/repo/oss/"}"}
+								_Product="Leap"
+								;;
+							"SLES")
+								: ${source_url:="${_SUSE_SLES_SOURCE:-"https://download.opensuse.org/distribution/leap/15.5/repo/oss/"}"}
+								_Product="SUSE"
+								;;
+							"Tumbleweed")
+								: ${source_url:="${_SUSE_TUMBLEWEED_SOURCE:-"https://download.opensuse.org/tumbleweed/repo/oss/"}"}
+								_Product="openSUSE"
+								;;
+							*)
+								: ${source_url:="${_SUSE_LEAP_SOURCE:-"https://download.opensuse.org/distribution/openSUSE-current/repo/oss/"}"}
+								_Product="Leap"
+								;;
+						esac
 					else
 						write_error "⛔ Unknown product selection: $2"
 						return 1
@@ -15132,25 +15153,6 @@ kvm::make_vm_now_from_opensuse_org() {
 	# Discover if the appropriate VM net interface is (default or br'0 - n')
 	: ${virt_net="$(system::find_vm_bridge)"}
 
-	# Set the default source URL for the SUSE version if not already set...
-	# NOTE: Using --source_url first, then the global variable (from _locations.info), then the default.
-	if [[ -z "${source_url}" ]]; then
-		case ${_UserProductSelection} in
-		"Leap")
-			: ${source_url:="${_SUSE_LEAP_SOURCE:-"https://download.opensuse.org/distribution/openSUSE-current/repo/oss/"}"}
-			;;
-		"SLES")
-			: ${source_url:="${_SUSE_SLES_SOURCE:-"https://download.opensuse.org/distribution/leap/15.5/repo/oss/"}"}
-			;;
-		"Tumbleweed")
-			: ${source_url:="${_SUSE_TUMBLEWEED_SOURCE:-"https://download.opensuse.org/tumbleweed/repo/oss/"}"}
-			;;
-		*)
-			: ${source_url:="${_SUSE_LEAP_SOURCE:-"https://download.opensuse.org/distribution/openSUSE-current/repo/oss/"}"}
-			;;
-		esac
-	fi
-
 	local vm_name="Template_SUSE_${CONFIG}_$(date +%Y-%m-%d-%H-%M)"
 
 	_summary_message="
@@ -15180,7 +15182,7 @@ kvm::make_vm_now_from_opensuse_org() {
 			--noautoconsole || (read -p "💥 - An ERROR has occurred. Please press [ENTER] to continue..." && return 1)
 	} 2>&1 | tee -a ${_LOGFILE} && dialog::display_summary_message "NOTICE!"
 
-	for i in PRESEED_FILE vm_kernel vm_initrd source_url CONFIG distro; do unset $i; done
+	for i in PRESEED_FILE vm_kernel vm_initrd source_url CONFIG distro _UserProductSelection _autoyast_filename ; do unset $i; done
 }
 
 kvm::make_vm_now_from_debian_org() {
@@ -17610,15 +17612,13 @@ template::AutoYast_xml() {
 			<package>acpi</package>
 			<package>pciutils</package>
 			<package>jq</package>
-			<package>p7zip-full</package>
 			<package>xhost</package>
 			<package>rsync</package>
 			</packages>
 
 			<products config:type="list">
-			<product>${_UserProductSelection:-"Leap"}</product>
+			<product>${_Product:-"Leap"}</product>
 			</products>
-
 		</software>
 
 		<firstboot>
@@ -17846,14 +17846,14 @@ EOF
 )
 
 common_cleanup_config=$(cat <<EOF
-	- echo '******************* Common Cleanup Pre-Config ********************'
+        - echo '******************* Common Cleanup Pre-Config ********************'
 
         # Force unmounting of the target and other filesystems
-        - curtin in-target --target=/target -- /bin/bash -c 'umount -l /dev || true'
-        - curtin in-target --target=/target -- /bin/bash -c 'umount -l /cdrom || true'
-        - curtin in-target --target=/target -- /bin/bash -c 'umount -l /proc || true'
-        - curtin in-target --target=/target -- /bin/bash -c 'umount -l /sys || true'
-        - curtin in-target --target=/target -- /bin/bash -c 'umount -l /run || true'
+        # - curtin in-target --target=/target -- /bin/bash -c 'umount -l /dev || true'
+        # - curtin in-target --target=/target -- /bin/bash -c 'umount -l /cdrom || true'
+        # - curtin in-target --target=/target -- /bin/bash -c 'umount -l /proc || true'
+        # - curtin in-target --target=/target -- /bin/bash -c 'umount -l /sys || true'
+        # - curtin in-target --target=/target -- /bin/bash -c 'umount -l /run || true'
         - umount -l /cdrom || true
         - eject --force /dev/sr0 || true
         - eject --force /dev/sr1 || true
@@ -17899,7 +17899,6 @@ autoinstall:
         - p7zip-full
         - byobu
         - vim
-        - neofetch
         - jq
         - spice-vdagent
 EOF
@@ -17919,11 +17918,12 @@ cat >>${user_data_file} <<EOF
 ${common_vdi_pre_config}
 
         # Install Kubuntu Desktop Environment
-        - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install kubuntu-desktop'
+        - curtin in-target --target=/target -- /bin/bash -c 'for i in {1..3}; do apt-get -y install kubuntu-desktop || apt-get upgrade -y || true ; done'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install plymouth-theme-kubuntu-logo plymouth-theme-kubuntu-text plymouth-theme-spinner && update-initramfs -u ; exit 0'
         - curtin in-target --target=/target -- /bin/bash -c 'systemctl set-default graphical.target ; exit 0'
 
 ${common_vdi_post_config}
+${common_cleanup_config}
 EOF
 	# -----------------------------------------------------------------------------------------
 	;;
@@ -17940,13 +17940,18 @@ cat >>${user_data_file} <<EOF
 ${common_vdi_pre_config}
 
         # Install Ubuntu Desktop Environment
-        - curtin in-target --target=/target -- /bin/bash -c 'apt-get update -y'
-        - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install ubuntu-desktop-minimal'
-        - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install firefox || true'
+        - curtin in-target --target=/target -- /bin/bash -c 'apt install snapd -y '
+        - curtin in-target --target=/target -- /bin/bash -c 'systemctl start snapd.socket'
+        - curtin in-target --target=/target -- /bin/bash -c 'systemctl start snapd.service '
+        - curtin in-target --target=/target -- /bin/bash -c 'snap install snapd '
+        - curtin in-target --target=/target -- /bin/bash -c 'for i in {1..3}; do apt-get -y install ubuntu-desktop || apt-get upgrade -y || true ; done'
+        - curtin in-target --target=/target -- /bin/bash -c 'snap install firefox'
+        - curtin in-target --target=/target -- /bin/bash -c 'snap install snap-store'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install plymouth-theme-ubuntu-text plymouth-theme-spinner plymouth || true'
         - curtin in-target --target=/target -- systemctl disable systemd-networkd-wait-online.service || true
 
 ${common_vdi_post_config}
+${common_cleanup_config}
 EOF
 	# -----------------------------------------------------------------------------------------
 	;;
@@ -17963,7 +17968,7 @@ ${common_vdi_pre_config}
         # Install xubuntu-desktop
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get update -y'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get upgrade -y'
-        - curtin in-target --target=/target -- apt-get -y install xubuntu-desktop
+        - curtin in-target --target=/target -- /bin/bash -c 'for i in {1..3}; do apt-get -y install xubuntu-desktop && break || { printf "Attempt %d failed\n" "$i" >&2; sleep 5; }; done'
         - curtin in-target --target=/target -- apt install -y plymouth-theme-xubuntu-logo plymouth-theme-xubuntu-logo plymouth-theme-spinner plymouth-x11 ; update-initramfs -u ; exit 0
 
 ${common_vdi_post_config}
@@ -17984,7 +17989,7 @@ ${common_vdi_pre_config}
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get update -y'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get upgrade -y'
         - curtin in-target --target=/target -- /bin/bash -c "echo lightdm shared/default-x-display-manager select lightdm | debconf-set-selections"
-        - curtin in-target --target=/target -- apt-get -y install ubuntu-mate-desktop
+        - curtin in-target --target=/target -- /bin/bash -c 'for i in {1..3}; do apt-get -y install ubuntu-mate-desktop && break || { printf "Attempt %d failed\n" "$i" >&2; sleep 5; }; done'
         - curtin in-target --target=/target -- apt-get -y install plymouth-theme-ubuntu-mate-logo plymouth-theme-ubuntu-mate-text plymouth-theme-spinner plymouth-x11 ; update-initramfs -u ; exit 0
         - curtin in-target --target=/target -- systemctl set-default graphical.target  ; exit 0
         - curtin in-target --target=/target -- systemctl disable systemd-networkd-wait-online.service ; exit 0
@@ -18006,7 +18011,7 @@ ${common_vdi_pre_config}
         # Install Lubuntu Desktop
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get update -y'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get upgrade -y'
-        - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install lubuntu-desktop'
+        - curtin in-target --target=/target -- /bin/bash -c 'for i in {1..3}; do apt-get -y install lubuntu-desktop && break || { printf "Attempt %d failed\n" "$i" >&2; sleep 5; }; done'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install plymouth-theme-lubuntu-logo plymouth-theme-lubuntu-text ; update-initramfs -u ; || true'
  
 ${common_vdi_post_config}
@@ -18026,7 +18031,7 @@ ${common_vdi_pre_config}
         # Install Cinnamon Desktop
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get update -y'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get upgrade -y'
-        - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install cinnamon-desktop-environment'
+        - curtin in-target --target=/target -- /bin/bash -c 'for i in {1..3}; do apt-get -y install cinnamon-desktop-environment && break || { printf "Attempt %d failed\n" "$i" >&2; sleep 5; }; done'
         - curtin in-target --target=/target -- /bin/bash -c 'apt-get -y install plymouth-theme-ubuntucinnamon-spinner ; update-initramfs -u ; exit 0'
 
 ${common_vdi_post_config}
