...

diff --git a/core/_rtd_library b/core/_rtd_library
--- a/core/_rtd_library
+++ b/core/_rtd_library
@@ -14833,27 +14833,45 @@ kvm::make_vm_now_from_fedora_org() {
 	: "${virt_net="$(system::find_vm_bridge)"}"
 	: "${BIN_VIRT_INSTALL:=$(type -p virt-install)}"
 	: "${_DEFAULT_FEDORA_VER:="$(curl -s https://dl.fedoraproject.org/pub/fedora/linux/releases/ | grep -oP 'href="\K[0-9]+(?=/")' | sort -n | tail -1)"}"
-	: "${_os_version=$($RTD_GUI --title "🐧 Select Release Version of Fedora" --inputbox "Please pick an available OS version by entering it below. \
-	If you are not sure just let me choose for you... Please NOTE: fedora is sort of a permanent beta and the anaconda installer may behave in unexpected ways. \n ${fedoralogo} " 25 110 "${_DEFAULT_FEDORA_VER:-"40"}" 3>&1 1>&2 2>&3)}"
-	case $? in
-	"$DIALOG_CANCEL") return ;;
-	"$DIALOG_ESC") return ;;
-	esac
-	clear
+
+	while [[ $# -gt 0 ]]; do
+		system::log_item "Processing argument: $1"
+		case "$1" in 
+			--fedora-version|-v|--version)
+				if [[ "$2" == "auto" ]]; then
+					_skip_prompt="TRUE"
+				fi
+				shift 2
+			;;
+			*)
+				shift
+			;;
+		esac
+	done
+
+	if [[ "$_skip_prompt" != "TRUE" ]]; then
+		: "${_os_version=$($RTD_GUI --title "🐧 Select Release Version of Fedora" --inputbox "Please pick an available OS version by entering it below. \
+		If you are not sure just let me choose for you... Please NOTE: fedora is sort of a permanent beta and the anaconda installer may behave in unexpected ways. \n ${fedoralogo} " 25 110 "${_DEFAULT_FEDORA_VER:-"40"}" 3>&1 1>&2 2>&3)}"
+		case $? in
+		"$DIALOG_CANCEL") return ;;
+		"$DIALOG_ESC") return ;;
+		esac
+		clear
+	fi
 
 	: "${_os_version:="${_DEFAULT_FEDORA_VER}"}"
-	: "${_mirrorlist_url="https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-${_os_version}&arch=x86_64"}"
-	: "${_source_url:="https://dl.fedoraproject.org/pub/fedora/linux/releases/${_os_version}/Everything/x86_64/os/"}"
 	: "${_preseed_file="$(mktemp -d)/ks.cfg"}"
 	
-	if [[ ${_role} == "workstation" || ${_role} == "VDI" ]]; then
-		kvm::get_fedora_workstation_iso --version ${_os_version} || {
-			write_error "Failed to fetch Fedora Workstation ISO. Please check your network connection or the Fedora repository."
-			return 1
-		}
-		write_information "Using Fedora Workstation ISO: ${iso}"
-		: ${fedora_iso_mount_point="/var/lib/libvirt/boot/Fedora_${_os_version}.iso_${RANDOM}"}
+	# Get Fedora media if not already present:
+	if kvm::get_fedora_workstation_iso --version ${_os_version} ; then 
+		system::log_item "Using Fedora Workstation ISO: ${iso}"
+	else 
+		write_error "Failed to fetch Fedora ${_os_version} Workstation ISO. Please check your network connection or the Fedora repository."
+		return 1
+	fi
 
+	# Check if target is workstation or server:
+	if [[ ${_role} == "workstation" || ${_role} == "VDI" ]]; then
 		local _service="VDI"
 		system::generate_ks_cfg_file --source "${_source_url}" --role "${_role}" --file "${_preseed_file}" --DE "${_UserDesktopEnvironmentSelection:="@basic-desktop-environment"}"
 	elif [[ ${_role} == "server" ]]; then
@@ -14870,26 +14888,16 @@ kvm::make_vm_now_from_fedora_org() {
 		return 1
 	else 
 		system::log_item "Using ISO file: ${iso}"
-		system::log_item "Mounting ISO at: ${fedora_iso_mount_point}"
-		mkdir -p "${fedora_iso_mount_point}" || {
-			write_error "Failed to create mount point: ${fedora_iso_mount_point}"
-			return 1
-		}
-		mount -o loop "${iso}" ${fedora_iso_mount_point} || {
-			write_error "Failed to mount ISO file: ${iso} at ${fedora_iso_mount_point}"
-			return 1
-		}
 		local vm_kernel="${fedora_iso_mount_point}/boot/grub2/i386-pc/kernel.exec"
 		local vm_initrd="${fedora_iso_mount_point}/boot/grub2/i386-pc/lnxboot.image"
 	fi
-
 
 	local vm_name="Template_Fedora_${_service}_$(date +%Y-%m-%d-%H-%M)"
 
 	_summary_message="The virtual machine (${vm_name}) \n
 	📋 - Using the instructions in Kickstart: ${_preseed_file} \n
 	🔧 - Using this source for the packages and files to download: \n
-	🌎 - ${_source_url} \n
+	🌎 - ${iso} \n
 	🖥️ - Using the network: ${virt_net:=default} \n
 	🖥️ - Memory: ${_mem} \n
 	🖥️ - CPU's: ${_cpu} \n
@@ -14909,12 +14917,7 @@ kvm::make_vm_now_from_fedora_org() {
 			--noautoconsole || (read -p "💥 - An ERROR has occurred. Please press [ENTER] to continue..." && return 1)
 	} 2>&1 | tee -a ${_LOGFILE} && dialog::display_summary_message "NOTICE!"
 	
-	# umount -l "${fedora_iso_mount_point}" || {
-	# 	write_error "Failed to unmount the ISO mount point: ${fedora_iso_mount_point}"
-	# 	return 1
-	# } ,kernel=${vm_kernel},initrd=${vm_initrd}
-	# inst.stage2=hd:LABEL=Fedora-Live-WS-x86_64
-	# ${fedora_iso_mount_point},kernel=${vm_kernel},initrd=${vm_initrd}
+	# Cleanup 
 	unset _preseed_file vm_kernel vm_initrd _source_url _config _mirrorlist_url _os_version _summary_message distro _UserServerEnvironemtSelection _UserDesktopEnvironmentSelection _role _service
 	
 }
@@ -16755,7 +16758,7 @@ template::kickstart_cfg() {
 		cat >>"${_ks_file}" <<-KS_EOF
 			# Generated by: system::generate_ks_cfg_file by RTD Power Tools
 			# Choosing mode (graphical|text|cmdline [--non-interactive])
-			# text
+			text
 			firstboot --enable
 			keyboard --vckeymap=${Preference_InitialKeyboardLayout:-"us"} --xlayouts="${Preference_InitialKeyboardLayout:-"us"}"
 			lang en_US.UTF-8
@@ -16797,7 +16800,7 @@ template::kickstart_cfg() {
 		cat >>"${_ks_file}" <<-KS_EOF
 			# Generated by: system::generate_ks_cfg_file by RTD Power Tools
 			# Choosing mode (graphical|text|cmdline [--non-interactive])
-			# graphical
+			graphical
 			firstboot --disable
 			keyboard --vckeymap=${Preference_InitialKeyboardLayout} --xlayouts="${Preference_InitialKeyboardLayout}"
 			lang en_US.UTF-8
@@ -16808,16 +16811,22 @@ template::kickstart_cfg() {
 			zerombr
 			clearpart --all
 			autopart --nohome ${Preference_DiskEncryption_RH}
-			reboot
 			# uncomment to debug installation
 			# %onerror --halt
-			# reboot --eject
+			reboot --eject
 
 			%packages --retries 5 --timeout 20
 			${_UserDesktopEnvironmentSelection}
+			xorg-x11-server-Xorg
+			xorg-x11-drv-evdev
+			xorg-x11-drv-libinput
+			xorg-x11-xauth
+			mesa-dri-drivers
+			mesa-libGL
 			@system-tools
 			openssh-server
 			spice-vdagent
+			qemu-guest-agent
 			git
 			curl
 			dialog
@@ -16833,6 +16842,9 @@ template::kickstart_cfg() {
 			chmod 755 ${_OEM_DIR:-"/opt/rtd"}/core/rtd-oem-enable-config.sh
 			bash ${_OEM_DIR:-"/opt/rtd"}/core/rtd-oem-enable-config.sh
 			systemctl enable sshd
+			systemctl enable gdm
+			restorecon -Rv /usr/share/wayland-sessions /usr/share/xsessions
+			systemctl set-default graphical.target
 			%end
 		KS_EOF
 		return
