Overall Modifications
Changes locations of all files to a modular structure, added find logic to locate the rtd library, updated documentation, simplified install, sped up install overall.

diff --git a/modules/Simple-Support-Tool.mod/rtd-simple-support-tool b/modules/Simple-Support-Tool.mod/rtd-simple-support-tool
--- a/modules/Simple-Support-Tool.mod/rtd-simple-support-tool
+++ b/modules/Simple-Support-Tool.mod/rtd-simple-support-tool
@@ -3,7 +3,8 @@
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #:: Author(s):   	SLS, KLS, NB.  Buffalo Center, IA & Avarua, Cook Islands
-    RTD_Version=2.0
+	RTD_Version=2.0
+:	${GIT_Profile:=vonschutter}
 #::
 #::
 #::	Purpose: To simplify support tasks
@@ -120,7 +121,7 @@ export RTD_GUI="${RTD_GUI:=dialog --clear}"
 LOGFILE="${LOGDIR}/${ basename $0 }.log"
 
 # Seting entries to conform to internal naming standard for max compatability.
-_ERRLOGFILE="${LOGFILE}" 
+_ERRLOGFILE="${LOGFILE}"
 _LOGFILE="${LOGFILE}"
 
 
@@ -132,23 +133,28 @@ _LOGFILE="${LOGFILE}"
 #
 # Below please find the executive functions of this script. These are the functions
 # that actually do the work requested.
-#
-#
+
 check_rtd_library ()
 {
-        # Set library path if not defined:
-        rtd_library=${rtd_library:-"/opt/rtd/scripts/_rtd_library"}
+	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/_rtd_library
 
-        if [[ -f ${rtd_library} ]]; then
-                source ${rtd_library}
-        elif [[ ! -f ${rtd_library} ]]; then
-                echo "RTD Functions not found... "
-                echo "Trying to retrieve them..."
-                wget ${_rtd_library:-"https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library"}
-                source ./_rtd_library
-        else
-                exit 1
-        fi
+	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library ; then
+		# Library found in relative path...
+		write_information "${FUNCNAME[0]} 1 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library
+	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
+		# Library not found in relative path: search the typical location...
+		write_information "${FUNCNAME[0]} 2 Using: $(find /opt -name _rtd_library |grep -v bakup )"
+	elif wget ${_src_url} ; then
+		# Critical failure: downloaded copy from github.com
+		source ./_rtd_library
+	else
+		# Abot condition: No mitigation steps worked.
+		echo -e "RTD functions NOT loaded!"
+		echo -e " "
+		echo -e "Cannot ensure that the correct functionality is available"
+		echo -e "Quiting rather than cause potential damage..."
+		exit 1
+	fi
 }
 
 
@@ -233,7 +239,7 @@ display_notice () {
 	$RTD_GUI --backtitle "$BRANDING" \
 	--title "About $( basename $0 ) " \
 	--msgbox "
-	This tool is part of the RTD System Support Tools. 
+	This tool is part of the RTD System Support Tools.
 	The purpose of this tool is to simplify management remote and local.
 
 	This script simplifies:
@@ -243,11 +249,11 @@ display_notice () {
 	- Perform distribution upgrades (supported distributions)
 	- Remove unused PPA's (where relevant)
 	- Display system information and resource usage
-	
-	To use this tool simply execute it: $( basename $0 ) 
-	This tool is usefull for support staff that do not live on the comman line daily, and 
-	can be used over ssh. If you do get disconnected the tool will remain active remotley 
-	and you can easily reconnect to it by re-establishing your ssh connection and typing 
+
+	To use this tool simply execute it: $( basename $0 )
+	This tool is usefull for support staff that do not live on the comman line daily, and
+	can be used over ssh. If you do get disconnected the tool will remain active remotley
+	and you can easily reconnect to it by re-establishing your ssh connection and typing
 	the word: byobu in the terminal. "  $HEIGHT $WIDTH
 	clear
 }
@@ -1052,10 +1058,10 @@ if [[ -z "$BASH_VERSINFO" ]]; then
 	exit 255
 fi
 
-case $1 in 
+case $1 in
 	about | --about | --help | -h )
 		display_notice				# Display script information
-		exit 
+		exit
 	;;
 	* )
 		if [[ "$TERM" == screen* ]]; then
diff --git a/modules/System_Admin.mod/rtd-7z-encrypt-this b/modules/System_Admin.mod/rtd-7z-encrypt-this
--- a/modules/System_Admin.mod/rtd-7z-encrypt-this
+++ b/modules/System_Admin.mod/rtd-7z-encrypt-this
@@ -4,8 +4,9 @@
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Compression Tool //::::::::::::::::::::::::::::::::::// Linux //::::::::
 #::
-#:: Author:   	SLS
-#:: Version 	1.02
+#::     Author:   	SLS
+#::     Version 	1.02
+:	${GIT_Profile:=vonschutter}
 #::
 #::
 #::	Purpose: To compress all files and folders provided as argument.
@@ -39,20 +40,25 @@
 
 check_rtd_library ()
 {
-        # Set library path if not defined:
-        scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-        rtd_library=${rtd_library:-"${scriptdir}/../../core/_rtd_library"}
+	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/_rtd_library
 
-        if [[ -f ${rtd_library} ]]; then
-                source ${rtd_library}
-        elif [[ ! -f ${rtd_library} ]]; then
-                echo "RTD Functions not found... "
-                echo "Trying to retrieve them..."
-                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
-                source ./_rtd_library
-        else
-                exit 1
-        fi
+	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library ; then
+		# Library found in relative path...
+		write_information "${FUNCNAME[0]} 1 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library
+	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
+		# Library not found in relative path: search the typical location...
+		write_information "${FUNCNAME[0]} 2 Using: $(find /opt -name _rtd_library |grep -v bakup )"
+	elif wget ${_src_url} ; then
+		# Critical failure: downloaded copy from github.com
+		source ./_rtd_library
+	else
+		# Abot condition: No mitigation steps worked.
+		echo -e "RTD functions NOT loaded!"
+		echo -e " "
+		echo -e "Cannot ensure that the correct functionality is available"
+		echo -e "Quiting rather than cause potential damage..."
+		exit 1
+	fi
 }
 
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
diff --git a/modules/System_Admin.mod/rtd-mv b/modules/System_Admin.mod/rtd-mv
--- a/modules/System_Admin.mod/rtd-mv
+++ b/modules/System_Admin.mod/rtd-mv
@@ -2,8 +2,9 @@
 #::                                 RTD System System Managment Script
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::// Simple Admin Tool //::::::::::::::::::::::::::::::::::::::::// Linux //::::::::
-#:: Author:     SLS.
-#:: Version:	1.03
+#::     Author:   	SLS
+#::     Version 	1.02
+:	${GIT_Profile:=vonschutter}
 #::
 #::
 #:: Purpose: The purpose of the script is to perform managment tasks on Linux systems
@@ -31,27 +32,33 @@ BRANDING="RTD Simple Support Tool: File type mover/collector "
 
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::                                          ::::::::::::::::::::::
-#::::::::::::::             INITIALIZE                   ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
 check_rtd_library ()
 {
-        # Set library path if not defined:
-        scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-        rtd_library=${rtd_library:-"${scriptdir}/../../core/_rtd_library"}
+	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/_rtd_library
 
-        if [[ -f ${rtd_library} ]]; then
-                source ${rtd_library}
-        elif [[ ! -f ${rtd_library} ]]; then
-                echo "RTD Functions not found... "
-                echo "Trying to retrieve them..."
-                wget https://github.com/vonschutter/RTD-Build/raw/master/System_Setup/_rtd_library
-                source ./_rtd_library
-        else
-                exit 1
-        fi
+	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library ; then
+		# Library found in relative path...
+		write_information "${FUNCNAME[0]} 1 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library
+	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
+		# Library not found in relative path: search the typical location...
+		write_information "${FUNCNAME[0]} 2 Using: $(find /opt -name _rtd_library |grep -v bakup )"
+	elif wget ${_src_url} ; then
+		# Critical failure: downloaded copy from github.com
+		source ./_rtd_library
+	else
+		# Abot condition: No mitigation steps worked.
+		echo -e "RTD functions NOT loaded!"
+		echo -e " "
+		echo -e "Cannot ensure that the correct functionality is available"
+		echo -e "Quiting rather than cause potential damage..."
+		exit 1
+	fi
 }
+
 
 me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
 filetype=$1
diff --git a/modules/System_Update.mod/rtd-update-system b/modules/System_Update.mod/rtd-update-system
--- a/modules/System_Update.mod/rtd-update-system
+++ b/modules/System_Update.mod/rtd-update-system
@@ -1,94 +1,116 @@
 #!/bin/bash
-PUBLICATION="RuntimeData Update Manager for Ubuntu"
-VERSION="1.13"
-#
-#	RTD Ubuntu + derivatives software update script
-#
-#
-# This system configuration and installation script was originally developed
-# for RuntimeData, a small OEM in Buffalo Center, IA. The purpose of the script
-# was to install and configure Ubuntu and Zorin OS PC's. This OEM and store nolonger
-# exists as its owner has passed away. This script is shared in the hopes that
-# someone will find it usefull.
-#
-# The purpose of this script is to update installed software from distribution reopositories.
-#
-###########################################################################
-##                                                                       ##
-##                       Set Environment                                 ##
-##                                                                       ##
-###########################################################################
-# Test comment...
+#::                                      A D M I N   C O M M A N D
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::// Simple Compression Tool //::::::::::::::::::::::::::::::::::// Linux //::::::::
+#::
+#:: 	Author:   	SLS
+:	${PUBLICATION:="RuntimeData Update Manager for Linux"}
+:	${VERSION:="1.13"}
+:	${GIT_Profile:=vonschutter}
+#::
+#::
+#::	Purpose: The purpose of this script is to update installed software from distribution reopositories.
+#::		 Software update script for SUSE, Debian, RedHat based systems...
+#::
+#::	Usage:	Simply execute this script to accomplish this task. No parameters required.
+#::
+#::	Change Log:
+#::		- 2006.06.15: File originally created
+#::		- 2015.10.15: Expanded to support multiple distros
+#::		- 2018.05.10: Expanded to support Flatpak and Snaps
+#::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+
+
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Settings                 ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+# Variables that govern the behavior or the script and location of files are
+
 # Set colors for prompting on screen.
 	YELLOW="\033[1;33m"
 	RED="\033[1;31m"
 	ENDCOLOR="\033[0m"
 	GREEN="\033[1;32m"
 	BLUE="\033[1;34m"
-	
+
 # Ensure administrative privileges.
-[ "$UID" -eq 0 ] && echo -e "Administrative Access OK" $ENDCOLOR || echo -e $YELLOW"This script needs administrative access..." $ENDCOLOR 
+[ "$UID" -eq 0 ] && echo -e "Administrative Access OK" $ENDCOLOR || echo -e $YELLOW"This script needs administrative access..." $ENDCOLOR
 [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
 
-# Identify 
-# clear	
+# Identify
+# clear
 echo -e $GREEN"$PUBLICATION: Version $VERSION" $ENDCOLOR
 echo -e $GREEN"--------------------------------------------------------" $ENDCOLOR
 
-echo This tool makes it simple to update software from all channels 
+echo This tool makes it simple to update software from all channels
 echo available on the system at once. It will update via the native
 echo -e "package manager as well as newer formats like $YELLOW"snap"$ENDCOLOR and $YELLOW"flatpak"$ENDCOLOR..."
-echo " " 
+echo " "
 echo This update script supports the following instructions:
 echo " "
-echo -e " - $YELLOW"Default"$ENDCOLOR : Just running this script will update via all configured channels."	
+echo -e " - $YELLOW"Default"$ENDCOLOR : Just running this script will update via all configured channels."
 echo -e " - $YELLOW"update"$ENDCOLOR :  Parameter "update" will update the updater to the latest version. "
 echo -e " - $YELLOW"setup"$ENDCOLOR :   Parameter "setup" make sure that you are using all software channels "
 echo -e "      "
 echo " "
 
-if [ "$1" == "update" ]; then 
+if [ "$1" == "update" ]; then
        	INSTRUCTION=update_me
 fi
 
-if [ "$1" == "config" ]; then 
+if [ "$1" == "config" ]; then
        	INSTRUCTION=config_me
 fi
 
-if [ "$1" == "setup" ]; then 
+if [ "$1" == "setup" ]; then
        	INSTRUCTION=setup_me
 fi
 
 
 
-# Enable RTD Functions...
-echo "Checking for RTD Functions..."
-FILE=/opt/rtd/scripts/_rtd_library
-if [ -f $FILE ]; then
-   echo -e $GREEN"RTD Functions are available: Loading them for use... " $ENDCOLOR
-   source $FILE
-else
-   echo "Cannot find RTD Functions... Attempting to get them online... "
-   wget -q --show-progress https://github.com/vonschutter/RTD-Build/raw/master/"${FILE##*/}" -P /opt/rtd/scripts
-   if [ -f $FILE ]; then
-   	echo -e $GREEN"RTD Functions are available: Loading them for use... " $ENDCOLOR
-   	source $FILE
-   else
-   	echo -e $RED"RTD Functions could NOT be loaded; You must use the native options to install software... "$ENDCOLOR
-   	exit 
-   fi
-fi
 
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Functions                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
+check_rtd_library ()
+{
+	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/_rtd_library
 
+	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library ; then
+		# Library found in relative path...
+		write_information "${FUNCNAME[0]} 1 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library
+	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
+		# Library not found in relative path: search the typical location...
+		write_information "${FUNCNAME[0]} 2 Using: $(find /opt -name _rtd_library |grep -v bakup )"
+	elif wget ${_src_url} ; then
+		# Critical failure: downloaded copy from github.com
+		source ./_rtd_library
+	else
+		# Abot condition: No mitigation steps worked.
+		echo -e "RTD functions NOT loaded!"
+		echo -e " "
+		echo -e "Cannot ensure that the correct functionality is available"
+		echo -e "Quiting rather than cause potential damage..."
+		exit 1
+	fi
 
-
-###########################################################################
-##                                                                       ##
-##                         Functions                                     ##
-##                                                                       ##
-###########################################################################
-#
+	write_host -cyan "Libraries loaded"
+	write_status "Paths registered:
+	- Root directory of tools: 		_OEM_DIR="${scriptdir%/*}"
+	- Caching and download folder: 		_CACHE_DIR="${_OEM_DIR}/cache"
+	- Location of 3rd party apps:		_APP_DIR="${_OEM_DIR}/apps"
+	- Location of extension modules:	_MODS_DIR="${_OEM_DIR}/modules"
+	- Root tools folder: 			_CORE_DIR="${_OEM_DIR}/core"
+	- Location of log files:		_LOG_DIR=/var/log/${_TLA,,}
+	"
+}
 
 
 
@@ -103,16 +125,19 @@ echo "$DATE --- : $@" >> $0.log
 
 update_me ()
 {
-	rm $0.bak
-	mv $0 $0.bak
-        wget  --show-progress https://github.com/vonschutter/RTD-Build/raw/master/System_Update/${0##*/} -P ${0%/*} 
-        chmod +x $0
-        if [[ -e $0 ]]; then 
-        	return  0 
-        else
-        	cp $0.bak $0
-        	return 1 
-        fi 
+	if [[ -w $0 ]] ; then
+		rm $0.bak
+		mv $0 $0.bak
+		wget  --show-progress https://github.com/vonschutter/RTD-Setup/raw/main/modules/System_Update.mod/${0##*/} -P $0
+		chmod +x $0
+		if [[ -e $0 ]]; then
+			return  0
+		else
+			cp $0.bak $0
+			echo "Update failed: rolled back!"
+			return 1
+		fi
+	fi
 }
 
 
@@ -131,31 +156,26 @@ setup_me ()
 	check_dependencies  snapd
 }
 
-###########################################################################
-##                                                                       ##
-##                        Execute updates                                ##
-##                                                                       ##
-###########################################################################
-#
-#
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::          Script Executive                ::::::::::::::::::::::
+#::::::::::::::                                          ::::::::::::::::::::::
+#::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-# Execute the fist instruction passed to this script... 
+check_rtd_library
+
+# Execute the fist instruction passed to this script...
 if [ ! -z $INSTRUCTION ]; then
-	log_item The instruction $INSTRUCTION was given... 
+	log_item The instruction $INSTRUCTION was given...
 	$INSTRUCTION
 	exit
 else
-	log_item No instructions passed to $0... Continuing with default behavior. 
+	log_item No instructions passed to $0... Continuing with default behavior.
 fi
 
-write_status "Updating installed software..." 
+write_status "Updating installed software..."
 
 # Updating software managed by distribution speciffic software manager...
-# Unless the RTD Functions are loaded, then use that. 
+# Unless the RTD Functions are loaded, then use that.
 
 rtd_update_system
-
-
-
-
-
diff --git a/modules/System_User_Backup.mod/rtd-oem-backup-linux-config b/modules/System_User_Backup.mod/rtd-oem-backup-linux-config
--- a/modules/System_User_Backup.mod/rtd-oem-backup-linux-config
+++ b/modules/System_User_Backup.mod/rtd-oem-backup-linux-config
@@ -5,19 +5,21 @@ VERSION="1.00"
 #::             RTD Ubuntu + derivatives backup script
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#:: Author:   	SLS 
 #::
+#::     Author:   	SLS
+#::     Version 	1.02
+:	${GIT_Profile:=vonschutter}
 #::
-#::	Purpose: The purpose of the script is to backup a users setings 
+#::	Purpose: The purpose of the script is to backup a users setings
 #::              and dokuments to some useful location.
 #::
 #:: This system configuration and installation script was originally developed
-#:: for RuntimeData, a small OEM in Buffalo Center, IA. 
+#:: for RuntimeData, a small OEM in Buffalo Center, IA.
 #::
-#:: RTD admin scrips are placed in /opt/rtd/scripts. This configuration script is mainly built to use 
-#:: functions in _rtd_functions and _rtd_recipies. 
-#::       _rtd_functions -- contain usefull admin functions for scripts, such as "how to install software" on different systems. 
-#::       
+#:: RTD admin scrips are placed in /opt/rtd/scripts. This configuration script is mainly built to use
+#:: functions in _rtd_functions and _rtd_recipies.
+#::       _rtd_functions -- contain usefull admin functions for scripts, such as "how to install software" on different systems.
+#::
 #::
 #::
 #::
@@ -33,18 +35,9 @@ VERSION="1.00"
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 #
 # You may comment out or edit items as you deem necessary.
-# Ensure that the  RTD Functions are available and load them... 
+# Ensure that the  RTD Functions are available and load them...
 # This contains most of the intelligence used to perform this systems
-# maintenance. 
-# 
-# the RTD Functions contain useful task functions (example): 
-#  -  check_dependencies
-#  -  ensure_admin
-#
-_FILE=_rtd_functions
-_RTD_S_HOME=/opt/rtd/scripts
-unset rtd_oem_user_backup_destination
-source $_RTD_S_HOME/$_FILE
+# maintenance.
 
 
 # Set the background tilte:
@@ -53,19 +46,19 @@ BACKTITLE="$PUBLICATION"
 # Set the options to appear in the menu as choices:
 option_1="Gnome Desktop Setings"
 option_2="Gnome Credentials Manager"
-option_3="Remmina Configuration" 
-option_4="Users Private Themes" 
-option_5="Users Private Icons" 
-option_6="Users Private Fonts " 
-option_7="Users Private Documents" 
-option_8="Users Private Pictures" 
-option_9="Firefox Settings" 
-option_10="Chrome Settings"  
-option_11="All VirtualBox VMs" 
-option_12="Teamviewer Configuration" 
+option_3="Remmina Configuration"
+option_4="Users Private Themes"
+option_5="Users Private Icons"
+option_6="Users Private Fonts "
+option_7="Users Private Documents"
+option_8="Users Private Pictures"
+option_9="Firefox Settings"
+option_10="Chrome Settings"
+option_11="All VirtualBox VMs"
+option_12="Teamviewer Configuration"
 option_13="Backup entire HOME folder"
 option_14="Backup All Virtual Machines (KVM)"
-                   
+
 
 
 
@@ -75,15 +68,38 @@ option_14="Backup All Virtual Machines (KVM)"
 #::::::::::::::          Script Functions                ::::::::::::::::::::::
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
-#
+
+check_rtd_library ()
+{
+	_src_url=https://github.com/${_GIT_PROFILE}/RTD-Setup/raw/main/core/_rtd_library
+
+	if source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library ; then
+		# Library found in relative path...
+		write_information "${FUNCNAME[0]} 1 Using:  $( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/../../core/_rtd_library
+	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
+		# Library not found in relative path: search the typical location...
+		write_information "${FUNCNAME[0]} 2 Using: $(find /opt -name _rtd_library |grep -v bakup )"
+	elif wget ${_src_url} ; then
+		# Critical failure: downloaded copy from github.com
+		source ./_rtd_library
+	else
+		# Abot condition: No mitigation steps worked.
+		echo -e "RTD functions NOT loaded!"
+		echo -e " "
+		echo -e "Cannot ensure that the correct functionality is available"
+		echo -e "Quiting rather than cause potential damage..."
+		exit 1
+	fi
+}
 
 
 
-# Function to request an encryption phrase. 
-# This prase will be used to encrypt the compressed archives. 
+
+# Function to request an encryption phrase.
+# This prase will be used to encrypt the compressed archives.
 zenity_ask_for_encryption_pass_phrase () {
 	check_dependencies zenity
-    	passtoken=$(zenity --title "Encryption Password" --password ) 
+    	passtoken=$(zenity --title "Encryption Password" --password )
     	if [[ -z "$passtoken" ]]; then
                 zenity --warning --text="Your settings likely contain sensitive information and should be encrypted! Please set a pass phrase"
 		zenity_ask_for_encryption_pass_phrase
@@ -92,7 +108,7 @@ zenity_ask_for_encryption_pass_phrase () {
 
 
 
-# Function to display the backup otions above. This is all done in a bit of a 
+# Function to display the backup otions above. This is all done in a bit of a
 # round about way... but the idea is to prepare this setup to be flexible
 # for the future so that you only have one place to list the option while
 # more than one gui toolkit (dialog, zenity, whiptail) depending on your environment.
@@ -121,40 +137,40 @@ zenity_show_list_of_user_backup_choices () {
 
 
 
-# Simple function to display a infromational notice when the tool is envoked. 
+# Simple function to display a infromational notice when the tool is envoked.
 rtd_oem_user_backup_info_notice() {
 
 	zenity --info --width=800 --height=400 --text="
 
-The RTD User Backup tool is a simple tool to allow anyone to backup important files and/or the entire home folder to an external USB drive as a backup ahead of re-installing a PC from scratch. 
+The RTD User Backup tool is a simple tool to allow anyone to backup important files and/or the entire home folder to an external USB drive as a backup ahead of re-installing a PC from scratch.
 
-It is highly recommended to encrypt all content so that is cannot easily be stolen. Do remember the password or you will never be able to access the backed-up content ever again. 
+It is highly recommended to encrypt all content so that is cannot easily be stolen. Do remember the password or you will never be able to access the backed-up content ever again.
 
-You will need the following: 
+You will need the following:
 1 - An external drive
 2 - A good password
 
-The RTD Backup tool will encrypt, compress and save all the information in the location provided. 
+The RTD Backup tool will encrypt, compress and save all the information in the location provided.
 	"
 }
 
 
 
-# Dialog to request the destination of where to store the compressed and encrypted archive. 
+# Dialog to request the destination of where to store the compressed and encrypted archive.
 rtd_oem_request_user_backup_destination() {
 	if [[ -z "$rtd_oem_user_backup_destination" ]]; then
 		export rtd_oem_user_backup_destination=$( zenity --width=800 --height=400 --text "$BACKTITLE" --file-selection --directory  )
 	elif [[ -n "$string" ]]; then
 		echo "Saving Backup to: $rtd_oem_user_backup_destination"
-	fi	
+	fi
 }
-	
+
 
 
 # Notify end user thes backup tasks are complete.
-rtd_oem_user_backup_info_notice_complete() { 
+rtd_oem_user_backup_info_notice_complete() {
 	zenity --info --width=800 --height=400 --text="
-Backup is complete. Please revise the list below. 
+Backup is complete. Please revise the list below.
 
 Backup archive(s) saved to:
 $rtd_oem_user_backup_destination
@@ -174,29 +190,29 @@ rtd_oem_cleanup() {
 }
 
 
-	
-# Function to execute the given backup and encryption task. Levels of compression and 
+
+# Function to execute the given backup and encryption task. Levels of compression and
 # other option may be set in the seting section of this script (tool)
 rtd_user_bak () {
-	rtd_oem_request_user_backup_destination 
-	echo ... > $rtd_oem_user_backup_destination/flg 
+	rtd_oem_request_user_backup_destination
+	echo ... > $rtd_oem_user_backup_destination/flg
 	if [[ -e $rtd_oem_user_backup_destination/flg ]]; then
 		rm $rtd_oem_user_backup_destination/flg
-		if [[ -d $2 ]]; then 
+		if [[ -d $2 ]]; then
 			7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p$passtoken $rtd_oem_user_backup_destination/`whoami`-"$1"-`date -u --iso-8601`.7z "${@:2}"
-		else 
+		else
 			echo "Backup source $2 does not exist..."
-		fi 
-	else 
+		fi
+	else
 		zenity --info --width=800 --height=400 --text="$rtd_oem_user_backup_destination is not writable! Plese select another destination."
 		rtd_oem_request_user_backup_destination
 	fi
-}	
+}
 
 
-		
-# Function to do what the choices instruct. We read the output from 
-# the choices and execute commands that accomplish the task requested. 
+
+# Function to do what the choices instruct. We read the output from
+# the choices and execute commands that accomplish the task requested.
 do_instructions_from_choices (){
         IFS=$','
 	for choice in $choices
@@ -219,10 +235,10 @@ do_instructions_from_choices (){
 			echo $passtoken |sudo -S chmod 777 -R /var/lib/libvirt
 			rtd_user_bak "$option_14" /var/lib/libvirt
 			echo $passtoken |sudo -S  chmod 750 -R /var/lib/libvirt
-			echo $passtoken |sudo -S  chown -R libvirt-qemu /var/lib/libvirt 
+			echo $passtoken |sudo -S  chown -R libvirt-qemu /var/lib/libvirt
 		;;
 		esac
-	done  
+	done
 }
 
 
@@ -235,18 +251,19 @@ do_instructions_from_choices (){
 #
 #
 # Software and configuration selections dialog. This will present a number of OEM defaults
-# and other preferences that can be added to a system at will. To remove software it is 
+# and other preferences that can be added to a system at will. To remove software it is
 # recommended to use the native software tool (Gnome Software, Yast, or Discover).
 #
 # Option defaults may be set to "on" or "off"
 
 # "dialog" will be used to request interactive configuration...
-# Ensure that it is available: 
+# Ensure that it is available:
 trap "passtoken=nonsense" 0 1 2 5 15
+check_rtd_library
 rtd_oem_user_backup_info_notice
 zenity_ask_for_encryption_pass_phrase
 zenity_show_list_of_user_backup_choices
-do_instructions_from_choices 
+do_instructions_from_choices
 rtd_oem_user_backup_info_notice_complete
 
 
@@ -270,22 +287,22 @@ exit
 
 
 function fallback_show_list_of_user_backup_choices () {
-
+	check_rtd_library
         check_dependencies whiptail
         cmd=(whiptail --separate-output --backtitle "$BACKTITLE" --title "What to backup" --checklist "Please Select what you want to backup below:" 22 85 18 )
-        optionlist=( 1 "Gnome Setings" ON 
-                     2 "Gnome Credentials Manager" ON 
-                     3 "Remmina Configuration" ON 
-                     4 "Users Private Themes" ON 
-                     5 "Users Private Icons" ON 
-                     6 "Users Private Fonts " ON 
-                     7 "Users Private Documents" ON 
-                     8 "Users Private Pictures" ON 
-                     9 "Firefox Settings" ON 
-                     10 "Chrome Settings"  ON 
-                     11 "VirtualBox VM's (may be really large files and take time)" ON 
-                     12 "Teamviewer Configuration" ON 
-		     12 "Entire HOME Folder" ON 
+        optionlist=( 1 "Gnome Setings" ON
+                     2 "Gnome Credentials Manager" ON
+                     3 "Remmina Configuration" ON
+                     4 "Users Private Themes" ON
+                     5 "Users Private Icons" ON
+                     6 "Users Private Fonts " ON
+                     7 "Users Private Documents" ON
+                     8 "Users Private Pictures" ON
+                     9 "Firefox Settings" ON
+                     10 "Chrome Settings"  ON
+                     11 "VirtualBox VM's (may be really large files and take time)" ON
+                     12 "Teamviewer Configuration" ON
+		     12 "Entire HOME Folder" ON
                      )
 }
 
