Change:
- library load time
- dtype
- enable config

diff --git a/modules/oem-bundle-manager/rtd-oem-bundle-manager b/modules/oem-bundle-manager/rtd-oem-bundle-manager
--- a/modules/oem-bundle-manager/rtd-oem-bundle-manager
+++ b/modules/oem-bundle-manager/rtd-oem-bundle-manager
@@ -231,14 +231,7 @@ system::ExecStart::help ()
 #::::::::::::::                                          ::::::::::::::::::::::
 #::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 
-
-
-if [ -z "${RTDFUNCTIONS}" ]; then
-	dependency::file "_rtd_library" || { echo "📚 Failed to find _rtd_library"; exit 1; }
-else
-	echo "📚 _rtd_library is already loaded..."
-fi
-
+dependency::file "_rtd_library" || { echo "📚 Failed to find _rtd_library"; exit 1; }
 
 case ${1} in
 	--help )
