nnn

diff --git a/modules/System_Update.mod/rtd-update-self b/modules/System_Update.mod/rtd-update-self
--- a/modules/System_Update.mod/rtd-update-self
+++ b/modules/System_Update.mod/rtd-update-self
@@ -73,19 +73,31 @@ export _STATUSLOG=${_LOG_DIR}/$(date +%Y-%m-%d-%H-%M-%S-%s)-oem-setup-status.log
 
 check_rtd_library ()
 {
-        # Set library path if not defined:
-        : ${rtd_library:="/opt/${_TLA,,}/core/_rtd_library"}
-
-        if [[ -f ${rtd_library} ]]; then
-                source ${rtd_library}
-        elif [[ ! -f ${rtd_library} ]]; then
-                echo "RTD Functions not found... "
-                echo "Trying to retrieve them..."
-                wget ${_src_url:="https://github.com/vonschutter/RTD-Setup/raw/master/core/_rtd_library"}
-                source ./_rtd_library
-        else
-                exit 1
-        fi
+	if  [[ -f "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/_rtd_library ]]; then
+		source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/_rtd_library
+	elif [[ -f "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/_rtd_library ]] ; then
+		source "$( cd "$( dirname "$(readlink -f ${BASH_SOURCE[0]})" )" && pwd )"/_rtd_library
+	elif source $(find /opt -name _rtd_library |grep -v bakup ) ; then
+		echo "Using: $(find /opt -name _rtd_library |grep -v bakup )"
+	else
+		echo -e "RTD functions NOT loaded!"
+		echo -e " "
+		echo -e "Cannot ensure that the correct functionality is available"
+		echo -e "Quiting rather than cause potential damage..."
+		exit 1
+	fi
+	write_host -cyan "Libraries loaded"
+	write_status "Paths registered:
+	* # Root directory of tools: 		_OEM_DIR="${scriptdir%/*}"
+	* # Caching and download folder: 	_CACHE_DIR="${_OEM_DIR}/cache"
+	* # Location of oem wallpapers: 	_WALLPAPER_DIR="${_OEM_DIR}/wallpaper"
+	* # Location of custom sounds:		_CUSTOMSOUND_DIR="${_OEM_DIR}/sound"
+	* # Location of installable themes: 	_THEME_DIR="${_OEM_DIR}/themes"
+	* # Location of 3rd party apps:		_APP_DIR="${_OEM_DIR}/apps"
+	* # Location of extension modules:	_MODS_DIR="${_OEM_DIR}/modules"
+	* # Root tools folder: 			_CORE_DIR="${_OEM_DIR}/core"
+	* # Location of log files:		_LOG_DIR=/var/log/${_TLA,,}
+	"
 }
 
 task_setup_rtd_basics() {
@@ -102,6 +114,7 @@ task_setup_rtd_basics() {
 				echo "Instructions successfully retrieved..."
 				if [[ -d /opt/${_TLA,,}  ]] ; then
 					mv /opt/${_TLA,,} /opt/${_TLA,,}.$(date +%Y-%m-%d-%H-%M-%S-%s).bakup
+					compress_provided_items /opt/${_TLA,,}.$(date +%Y-%m-%d-%H-%M-%S-%s).bakup $$ rm .r /opt/${_TLA,,}.$(date +%Y-%m-%d-%H-%M-%S-%s).bakup
 					mv /opt/${_TLA,,}.tmp /opt/${_TLA,,}
 				fi
 				source /opt/${_TLA,,}/core/_rtd_library
